# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Start web app (sine.tensorturtle.com)

on:
    push:
        branches: [ main ]
        paths-ignore:
          - '**/README.md'
    pull_request:
        branches: [ main ]
    schedule:
      - cron: '0 0 * * MON' # weekly on monday 00:00

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
    - name: Test with pytest
      run: |
          pytest -s

